import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-doctor-dashboard-overview',
  imports: [CommonModule],
  templateUrl: './over-view.component.html',
})
export class DoctorOverview {
  phone = '+20 0123456789';
  patientRequests = [
    {
      id: 1,
      name: 'Ahmed Ali',
      avatar: 'A',
      avatarColor: 'emerald',
      phone: this.phone,
      date: '2026-05-22',
      time: '04:30 PM',
      urgency: 'normal',
      type: 'consultation',
      status: 'pending',
      gender: 'male',
    },
    {
      id: 2,
      name: 'Sara Mohamed',
      avatar: 'S',
      avatarColor: 'pink',
      phone: this.phone,
      date: '2026-05-22',
      time: '05:15 PM',
      urgency: 'normal',
      type: 'follow-up',
      status: 'pending',
      gender: 'female',
    },
    {
      id: 3,
      name: 'Mohamed Ibrahim',
      avatar: 'M',
      avatarColor: 'emerald',
      phone: this.phone,
      date: '2026-05-23',
      time: '09:00 AM',
      urgency: 'medium',
      type: 'urgent-consultation',
      status: 'pending',
      gender: 'male',
    },
    {
      id: 4,
      name: 'Sare Ahmed',
      avatar: 'S',
      avatarColor: 'pink',
      phone: this.phone,
      date: '2026-05-23',
      time: '10:45 AM',
      urgency: 'high',
      type: 'emergency',
      status: 'pending',
      gender: 'male',
    },
    {
      id: 5,
      name: 'Ahmed Ali',
      avatar: 'A',
      avatarColor: 'emerald',
      phone: this.phone,
      date: '2026-05-22',
      time: '04:30 PM',
      urgency: 'normal',
      type: 'consultation',
      status: 'pending',
      gender: 'male',
    },
    {
      id: 6,
      name: 'Sara Mohamed',
      avatar: 'S',
      avatarColor: 'pink',
      phone: this.phone,
      date: '2026-05-22',
      time: '05:15 PM',
      urgency: 'normal',
      type: 'follow-up',
      status: 'pending',
      gender: 'female',
    },
  ];
}
